on:
  push:
    branches:
      - '*'
      - '!gh-pages/*'
      - '!releases/*'
name: simple-ci

jobs:
  matrix-build:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node: [12]
        os: [ubuntu-latest]
    name: build.${{ matrix.os }}.${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run compile
      - run: npx ava -u

